workflows:
  build:
    scripts:
      - name: Install dependencies
        command: |
          flutter pub get
      - name: Build Android App
        command: |
          flutter build apk

# Environment variables
environment:
  flutter_channel: "stable"
  flutter_version: "2.8.1"
  ANDROID_SDK_VERSION: "31"
  ANDROID_BUILD_TOOLS_VERSION: "31.0.0"

# Flutter version and channel
flutter:
  version: $flutter_version
  channel: $flutter_channel
