workflows:
  main:
    environment:
      node: latest

    scripts:
      # Install Cordova dependencies
      - name: Install Cordova dependencies
        script: npm install -g cordova

      # Add required platforms and plugins
      - name: Add platforms and plugins
        script: |
          cordova platform add ios
          cordova plugin add cordova-plugin-xxx
          cordova plugin add cordova-plugin-yyy

      # Build iOS app
      - name: Build iOS app
        script: |
          cordova build ios --release --device

      # Archive iOS app
      - name: Archive iOS app
        script: |
          xcodebuild archive -workspace ./platforms/ios/YourApp.xcworkspace -scheme YourApp -archivePath ./build/YourApp.xcarchive

      # Export IPA file
      - name: Export IPA file
        script: |
          xcodebuild -exportArchive -archivePath ./build/YourApp.xcarchive -exportOptionsPlist ./exportOptions.plist -exportPath ./build/YourApp.ipa

      # Publish IPA file as an artifact
      - name: Publish IPA file
        script: |
          curl -F "ipa=@./build/YourApp.ipa" \
          -H "Authorization: Bearer $CM_API_TOKEN" \
          -H "Content-Type: multipart/form-data" \
          https://api.codemagic.io/artifacts/upload

    artifacts:
      - build/YourApp.ipa
