workflows:
  main:
    name: Build IPA
    environment:
      vars:
        IONIC_CLI_VERSION: '6.16.3'
        XCODE_VERSION: '12.5'
    scripts:
      - name: Install dependencies
        script: |
          sudo npm install -g @ionic/cli@${IONIC_CLI_VERSION}
      - name: Build IPA
        script: |
          ionic cordova platform add ios
          ionic cordova build ios --prod --release --device --buildConfig build.json
          mkdir -p $HOME/build/outputs/ipa
          cp platforms/ios/build/device/*.ipa $HOME/build/outputs/ipa/app.ipa
    artifacts:
      - $HOME/build/outputs/ipa/app.ipa
