workflows:
  build:
    name: Build Android App
    jobs:
      build:
        name: Build Job
        runs-on: ubuntu-latest
        steps:
          # Checkout the code repository
          - name: Checkout code
            uses: actions/checkout@v2

          # Install Node.js and Cordova
          - name: Install Node.js and Cordova
            uses: actions/setup-node@v2
            with:
              node-version: 14
          - name: Install Cordova
            run: |
              npm install -g cordova@10.0.0

          # Install dependencies and build the app
          - name: Install dependencies and build app
            run: |
              npm install
              ionic cordova platform add android
              npm install -g cordova-res
              cordova-res android
              ionic cordova build android --prod --release

          # Upload the APK as an artifact
          - name: Upload APK
            uses: actions/upload-artifact@v2
            with:
              name: app-release
              path: app/platforms/android/app/build/outputs/apk/release/app-release.apk


