# codemagic.yaml

workflows:
  build-and-test:
    environment:
      vars:
        - IONIC_APP_ID: YOUR_IONIC_APP_ID
        - IONIC_BUILD_TYPE: PRODUCTION
        - IONIC_CLI_VERSION: LATEST
    scripts:
      - name: Install Node.js and Ionic CLI
        script: |
          curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g cordova ionic@${IONIC_CLI_VERSION}
      - name: Install dependencies and build the app
        script: |
          npm install
          ionic cordova prepare android --no-build
          ionic cordova prepare ios --no-build
          ionic build --prod
      - name: Run tests
        script: |
          ionic test
