workflows:
  build:
    name: Build and Test
    environment:
      cordova-android: latest
      cordova-ios: latest
    scripts:
      - name: Install Node.js and Ionic CLI
        script: |
          curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs
          sudo npm install -g @ionic/cli
          sudo npm install
      - name: Install Cordova platforms and plugins
        script: |
          sudo ionic cordova platform add android
          sudo ionic cordova platform add ios
          sudo ionic cordova plugin add cordova-plugin-device
          sudo ionic cordova plugin add cordova-plugin-splashscreen
          sudo ionic cordova plugin add cordova-plugin-statusbar
          sudo ionic cordova plugin add cordova-plugin-whitelist
      - name: Build and Test
        script: |
          sudo ionic cordova build android --prod --release
          sudo ionic cordova build ios --prod --release
          sudo ionic cordova run android --prod --release
          sudo ionic cordova run ios --prod --release
