workflows:
  ios:
    name: iOS Build
    environment:
      # set up environment variables here, if needed
    scripts:
      # any custom scripts or commands to run before building, if needed
    # set up the build step
    ios:
      xcode:
        version: "13.2.1"
      build:
        project_directory: .
        scheme: MyIonicApp
        configuration: Release
        args:
          - "-UseModernBuildSystem=0"
      artifacts:
        - MyApp.ipa
        - MyApp.app.dSYM.zip
