workflows:
  name: Android workflow
  environment:
    xcode: latest
    node: v16.11.1
    npm: 6        
  cache:
    cache_paths:
      - $CM_BUILD_DIR/node_modules
  scripts:
    - name: Install dependencies
      script: |
        npm install
        npm ci # equivalent of npm install for CI systems.
        # Requires package-lock.json or npm-shrinkwrap.json to be present
        npm install -g ionic
        ionic info
    - name: Add Android platform
      script: |
        set -x
        ionic cordova platform remove android --nosave
        ionic cordova platform add android \
          --confirm \
          --no-interactive \
          --no-resources 
    - name: Build Android
      script: |    
        APK_PATH=$(find platforms/android/app/build/outputs/apk/release -name "*.apk" | head -1)
        jarsigner \
          -sigalg SHA1withRSA \
          -digestalg SHA1 \
          -keystore $CM_KEYSTORE_PATH \
          -storepass $CM_KEYSTORE_PASSWORD \
          -keypass $CM_KEY_PASSWORD \
          $APK_PATH $CM_KEY_ALIAS 
#     artifacts:
#       - platforms/android/app/build/outputs/**/*.apk
#       - platforms/android/app/build/outputs/**/mapping.txt
#     publishing:
#       # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
#       email:
#         recipients:
#           - user_1@example.com
#           - user_2@example.com
