workflows:
  build-and-test:
    name: Build and Test
    environment:
      vars:
        ANDROID_HOME: /opt/android/sdk
        PATH: $PATH:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools
    scripts:
      - name: Install Dependencies
        script: |
          npm install
      - name: Build Android App
        script: |
          ionic cordova platform add android
          ionic cordova build android --prod --release
      - name: Run Tests
        script: |
          npm run test
      - name: Publish Artifacts
        script: |
          codemagic-artifacts publish ./platforms/android/app/build/outputs/apk/release/app-release.apk
