# Use the latest available build machine
os: osx

# Define the workflow
workflows:
  # Define the build workflow
  build:
    # Define the steps for the workflow
    # Install dependencies
    - name: Install dependencies
      script: |
        npm install -g cordova ionic
        npm install
    # Build the app
    - name: Build app
      script: |
        ionic cordova build ios --prod --release
        ionic cordova build android --prod --release
    # Archive the built artifacts
    - name: Archive artifacts
      artifacts:
        - platforms/ios/build/device/*.ipa
        - platforms/android/app/build/outputs/apk/release/*.apk
