workflows:
  build:
    environment:
      # specify the desired node version
      node:
        version: 14.x
      # specify the desired Cordova version
      cordova: 10.0.0
      # specify the desired Android SDK version
      android-sdk:
        version: "30.0.2"
    # your build steps here
