# codemagic.yaml

workflows:
  build-and-test:
   
  
    scripts:
      - name: Install Node.js and Ionic CLI
        script: |
          curl -sL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
          npm install -g npm@latest
          sudo chown -R 501:20 "/Users/builder/.npm
      - name: Install dependencies and build the app
        script: |
          npm install
          ionic cordova platform add android
          npm i -D -E @angular/cli
          ionic build --prod
      - name: Run tests
        script: |
          ionic test
