workflows:
  android_build:
    name: Android Build
    environment:
      vars:
        ANDROID_HOME: "/usr/local/android-sdk"
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    scripts:
      - name: Install Dependencies
        script: |
          apt-get update
          apt-get install -y openjdk-8-jdk-headless
          curl -sL https://deb.nodesource.com/setup_16.x | bash -
          apt-get install -y nodejs
          npm install -g @ionic/cli cordova
          ionic cordova prepare android
      - name: Build Android
        script: |
          cd platforms/android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
