version: 1.0.0
workflows:
 
  build:
    scripts:
      - |
        echo '*** Installing dependencies ***'
        npm install
        npm install -g cordova ionic
      - |
        echo '*** Building Android app ***'
        ionic cordova build android --prod --release -- --keystore=keystore.jks --alias=myalias --storePassword=$ANDROID_STORE_PASSWORD --password=$ANDROID_PASSWORD
    environment:

      BUILD_DIR: "platforms/android/app/build/outputs/apk/release"
