workflows:
  build:
    scripts:
      - echo "Building the app"
      - npm install
      - ionic cordova platform add android@9.1.0 ios@6.1.0
      - ionic cordova build android --prod --release -- --keystore=keystore.jks --alias=myalias

