workflows:
  build_and_test:
    environment:
      vars:
        # Add any required environment variables here
        ANDROID_SDK_ROOT: /opt/android-sdk
        ANDROID_HOME: /opt/android-sdk
    scripts:
      # Install required dependencies
        name: "Install dependencies"
        command: |
          # Install Node.js and required packages
          curl -sL https://deb.nodesource.com/setup_lts.x | bash -
          apt-get install -y nodejs
          npm install -g cordova ionic
          # Install Android SDK and accept licenses
          mkdir -p /opt/android-sdk/cmdline-tools
          cd /opt/android-sdk/cmdline-tools
          curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip sdk.zip
          rm sdk.zip
          echo y | ./bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT "platform-tools" "build-tools;30.0.3" "platforms;android-30" "extras;android;m2repository" "extras;google;m2repository"
      # Build and test the app
        name1: "Build and test app"
        command1: |
          ionic cordova platform add android
          ionic cordova build android
          ionic cordova run android --emulator --no-native-run
