workflows:
  build:
    name: Build Workflow
    environment:
      vars:
        # Define environment variables here
        - IONIC_CLI_VERSION: latest
        - ANDROID_SDK_VERSION: "30.0.3"
        - ANDROID_BUILD_TOOLS_VERSION: "30.0.3"
    scripts:
      # Install dependencies
      - name: Install Dependencies
        script: |
          npm install -g cordova ionic@${IONIC_CLI_VERSION}
          ionic cordova prepare
          npm install
      # Build Android app
      - name: Build Android App
        script: |
          ionic cordova build android --prod --release
    artifacts:
      # Define artifacts to persist here
      - build/outputs/
