workflows:
  version: 
  version: 1.0.0


  build-android:
    environment:
      node: "16.x"
      cordova: "latest"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false"
    scripts:
      - npm install
      - cordova platform add android@latest
      - cordova plugin add cordova-plugin-ionic-webview@latest
      - ionic cordova build android --prod --release -- --keystore=keystore.jks --alias=android
    artifacts:
      - build/outputs/apk/**/*.apk
