workflows:
  ios:
    name: iOS Build
    environment:
      vars:
        XCODE_SCHEME: "YourProjectName"
    scripts:
      - name: Install Dependencies
        script: |
          npm install -g ionic cordova
          npm install
      - name: Build iOS
        script: |
          ionic cordova build ios --prod --release --device
      - name: Archive
        script: |
          xcodebuild clean -project ./platforms/ios/YourProjectName.xcodeproj -configuration Release -alltargets
          xcodebuild archive -project ./platforms/ios/YourProjectName.xcodeproj -scheme $XCODE_SCHEME -configuration Release -archivePath ./build/YourProjectName.xcarchive
      - name: Export Archive
        script: |
          xcodebuild -exportArchive -archivePath ./build/YourProjectName.xcarchive
