workflows:
  build_and_test_android:
    name: Build and Test Android
    environment:
      # Set the Android SDK version
      FLUTTER_VERSION: stable
      ANDROID_API_LEVEL: 30
      ANDROID_BUILD_TOOLS_VERSION: 30.0.2
    scripts:
      # Install dependencies
      - name: Install Dependencies
        command: flutter pub get
      # Build the app
      - name: Build App
        command: flutter build apk
      # Run tests
      - name: Run Tests
        command: flutter test
    artifacts:
      # Save the APK file as an artifact
      - build/app/outputs/apk/release/app-release.apk
    android:
      # Set the target device to run tests on
      flavors:
        main:
          target: emulator-5554
      licenses:
        # Accept Android licenses
        - android-sdk-license-.+
