workflows:
  android_build:
    name: Android Build
    environment:
      vars:
        ANDROID_HOME: "/usr/local/android-sdk"
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    scripts:
      - name: Install Dependencies
        script: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          export PATH="/opt/homebrew/bin:$PATH"
          brew install openjdk@8
          brew install node
          npm install -g @ionic/cli cordova
          ionic cordova prepare android
      - name: Build Android
        script: |
          cd platforms/android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
