workflows:
  android-workflow:
    name: Android workflow
    # environment:
      # android_signing:
      #   - keystore_reference
      # groups:
      #   - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS - Put your google-services.json here)
      # xcode: 15.0.1
      # node: v12.22.12
      # npm: 6        
    cache:
      cache_paths:
        - $CM_BUILD_DIR/node_modules
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm ci ci # equivalent of npm install for CI systems.
            # Requires package-lock.json or npm-shrinkwrap.json to be present
          cvm install 9.0.0
          cvm use 9.0.0
          npm install -g ionic
          ionic info        
      - name: Add Android platform
        script: |
          set -x
          ionic cordova platform remove android --nosave
          ionic cordova platform add android \
            --confirm \
            --no-interactive \
            --noresources 
      - name: Build Android
        script: |    
          set -x
          set -e
          APK_PATH=$(find platforms/android/app/build/outputs/apk/release -name "*.apk" | head -1)
          jarsigner \
            -sigalg SHA1withRSA \
            -digestalg SHA1 \
            -keystore $CM_KEYSTORE_PATH \
            -storepass $CM_KEYSTORE_PASSWORD \
            -keypass $CM_KEY_PASSWORD \
            $APK_PATH $CM_KEY_ALIAS 
    artifacts:
      - platforms/android/app/build/outputs/**/*.apk
      - platforms/android/app/build/outputs/**/mapping.txt
    # publishing:
    #     # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
    #     email:
    #         recipients:
    #             - user_1@example.com
    #             - user_2@example.com
    #         notify:
    #           success: true     # To not receive a notification when a build succeeds
    #           failure: false    # To not receive a notification when a build fails
    #     slack: 
    #       # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
    #       channel: '#channel-name'
    #       notify_on_build_start: true   # To receive a notification when a build starts
    #       notify:
    #         success: true               # To not receive a notification when a build succeeds
    #         failure: false              # To not receive a notification when a build fails
    #     google_play:
    #       # See the following link for information regarding publishing to Google Play - https://docs.codemagic.io/publishing-yaml/distribution/#google-play
    #       credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
    #       track: alpha      
