workflows:
  android_build:
    name: Android Build
    environment:
      vars:
        ANDROID_HOME: "/usr/local/android-sdk"
        GRADLE_OPTS: "-Dorg.gradle.daemon=false"
      android:
        components:
          - platform-tools
          - tools
          - build-tools-29.0.3
          - android-29
          - extra-android-m2repository
    scripts:
      - name: Install Dependencies
        script: |
          npm install -g @ionic/cli cordova
          ionic cordova prepare android
      - name: Build Android
        script: |
          cd platforms/android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - your-email@example.com
