version: 1.0.0

workflows:
  main:
   - echo "Installing Cordova"
   - npm i -g cordova
   - echo "Installing dependencies"
   - npm install
   - echo "Building Cordova app"
   - ionic cordova build android --prod --release -- --keystore=keystore.jks --alias=my-alias-name
   - echo "Creating release APK"
   - cd $BUILD_DIR && jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1
    artifacts:
      - cordova/platforms/android/app/build/outputs/apk/release/*.apk

scripts:
  build:
    script:
      - echo "Setting up environment variables"
      - export FLAVOR="main"
      - export BUILD_DIR="cordova/platforms/android/app/build/outputs/apk/release"
      - echo "Building Android app"
      - cd cordova
      - ionic cordova build android --prod --release -- --keystore=keystore.jks --alias=myalias --storePassword=$ANDROID_STORE_PASSWORD --password=$ANDROID_PASSWORD -- --flavor=$FLAVOR --buildDir=$BUILD_DIR
    artifacts:
      - cordova/platforms/android/app/build/outputs/apk/release/*.apk
